kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: hello-develop
spec:
  replicas:
  template:
    metadata:
      name: hello
      labels:
        app: hello
        env: develop
        role: frontend
    spec:
      containers:
      - name: hello
        image: trustlab/cd-hello-app:latest
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /hello/
            port: 8888
