kind: Service
apiVersion: v1
metadata:
  name: hello-frontend
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8888
    protocol: TCP
  selector:
    app: hello
    role: frontend
